version: '3'
services:
    tasks:
        image: brendonmatheson/tasks:lin
        ports:
            - "9870:80"
        networks:
            - tasksbackend
        deploy:
            replicas: 5

    db:
        image: microsoft/mssql-server-linux:2017-GA
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_SA_PASSWORD: "p@ssw0rz@#"
        volumes:
            - tasks-db:/var/opt/mssql
        networks:
            - tasksbackend
        deploy:
            replicas: 1
            placement:
                constraints:
                    - "node.role==manager"

volumes:
    tasks-db:
        external: true

networks:
    tasksbackend:
        driver: overlay
